spring.application.name=food-service

server.port=8082
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MSS301_2026_PE_02;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=Dat200517@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.forward-headers-strategy=framework